### ISSUE TITLE
aws-nodejs-typescript template doesn't work

### ISSUE THREAD

**Issue by cohlar** [serverless/typescript#18]
The `aws-nodejs-typescript` create template doesn't work

<details>
<summary><code>serverless.ts</code></summary>

```ts
import type { AWS } from "@serverless/typescript";

import { hello } from "./src/functions";

const serverlessConfiguration: AWS = {
  service: "aws-nodejs-typescript",
  frameworkVersion: "2",
  custom: {
    webpack: {
      webpackConfig: "./webpack.config.js",
      includeModules: true,
    },
  },
  plugins: ["serverless-webpack"],
  provider: {
    name: "aws",
    runtime: "nodejs12.x",
    region: "eu-central-1",
    apiGateway: {
      minimumCompressionSize: 1024,
      shouldStartNameWithService: true,
    },
    environment: {
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1",
    },
    lambdaHashingVersion: "20201221",
  },
  functions: { hello },
};

module.exports = serverlessConfiguration;
```

</details>

<details>
<summary><b>The `hello` handler works when invoked locally. However once deployed to AWS and invoked, the execution fails with the following error:</b></summary>

```
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'handler'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module 'handler'",
    "Require stack:",
    "- /var/runtime/UserFunction.js",
    "- /var/runtime/index.js",
    "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:1015:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)",
    "    at Module.load (internal/modules/cjs/loader.js:879:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:724:14)",
    "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)",
    "    at internal/main/run_main_module.js:17:47"
  ]
}
```

</details>

<b>Installed version</b>

```
Framework Core: 2.18.0 (local)
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.4.7
```

**Comment by fredericbarthelet** [comment]
Hi @cohlar , thanks for reporting this issue. Could you please provide the request of invocation ? Meaning, considering you did not make any changes to `./src/functions/index.ts`, the HTTP request details you sent to your service ?

Your stack trace mention as well a `UserFunction.js` file, could you please provide the source code of this file as well ?

Thanks

**Comment by cohlar** [comment]
Hi @fredericbarthelet, thanks for responding so quickly!

I invoked the function manually in the AWS console ("Test" tab of the function, see screenshot below) with the following test event:
```
{
   "name": "Larry"
}
```

I've been wondering where this `UserFunction.js` is - it's nowhere in the repo. This is what I did:

1. Run `serverless create --template aws-nodejs-typescript`
2. Run `yarn`
3. Add  `region: "eu-central-1"` to `serverless.ts`
4. Run `yarn sls deploy`
5. Invoke the function manually in the AWS console (see screenshot below):

![image](https://user-images.githubusercontent.com/57757008/104609555-d5107300-568b-11eb-9a4d-f37973de6c0f.png)

I just pushed this into a repo for your convenience: https://github.com/cohlar/serverless-typescript

**Comment by fredericbarthelet** [comment]
Thanks for putting together a repo to demonstrate your point. I deployed your repo on my AWS account.
I tested the invocation as you deed, and did in fact saw an error. However my error message was different: `Cannot read property 'name' of undefined`. Can you share your node and yarn versions ? I see this as the last remaining discrepancy that could explain your error message.

In addition, your screenshot shows that the input event you defined, that is provided to lambda is:

```json
{
  "name": "Larry"
}
```

However, in nominal conditions, this lambda is invoked by API Gateway, which actually stringify HTTP request body in a `body` key within the event passed to lambda, such as:

```json
{
  "headers": {
    "Content-Type": "application/json"
  },
  "body": "{\"name\": \"Frederic\"}"
}
```

You can actually see the event the lambda expects from api gateway in `src/functions/hello/mock.json`

Using this latest event, I managed to get a successful execution on my stack 

![image](https://user-images.githubusercontent.com/23530626/104621936-f0ca4800-5690-11eb-99a6-9f7e8ac381d9.png)

**Comment by cohlar** [comment]
Hi,

Yes I understand, I was expecting to receive the same error message as you by not doing a `POST` request with a body.
I use node `v12.18.4` and yarn `1.22.5`.
I've reverted to the template version from commit sha `fef389b770a3f09431aa761dc98da8cd384eec3f`, and everything works perfectly for me there.

**Comment by cohlar** [comment]
Just wanted to share some additional feedback: I've encountered some issues with the output JavaScript code compiled by TypeScript. I fixed these by changing `ESNext` into `ES2015` (in `tsconfg.json` lib and target). I assume the reason is I use Node 12... since AWS Lambda doesn't support node runtimes beyond Node 12, I thought you may want to consider making this part of the default template as well, to avoid having code that works locally and fails once deployed.

**Comment by fredericbarthelet** [comment]
Thank you @cohlar for pointing this out. `ES2019` is in fact 100% compatible with nodejs 12 runtimes. I'll proceed with a PR to update this.

**Comment by fredericbarthelet** [comment]
@cohlar in order to help you on the issues you faced with the latest template version, could you provide me with the compiled contents of your `hello` function, as it was created by webpack ?

You can do that using S3 web interface, locating your stack deployement bucket and going down the file tree until you can download the `aws-nodejs-typescript.zip` file.

![image](https://user-images.githubusercontent.com/23530626/104908326-9bd74c00-5986-11eb-9204-0e3ca4e0f334.png)

Thanks in advance for your help.

**Comment by cohlar** [comment]
That repo is no longer on AWS. I just removed `.serverless` from `.gitgnore` and pushed, so you can find the zipped file here: https://github.com/cohlar/serverless-typescript/tree/main/.serverless

Let me know if that's good enough, otherwise I'll re-deploy

**Comment by fredericbarthelet** [comment]
Hi @cohlar, could you tel me which OS are you using ?
Could you as well tell me which path did you run your `sls deploy` command from ?

I think the code used to compute handler path may be facing issues depending on your OS (located in `lib/plugins/create/templates/aws-nodejs-typescript/src/functions/hello/index.ts` might be troubling)

**Comment by fredericbarthelet** [comment]
@cohlar, if you're still available, could you try replacing l.4 of `src/functions/hello/index.ts` with the following code :
```ts
handler: `src/functions/hello/handler.main`,
```
and see if it works

**Comment by cohlar** [comment]
Hi @fredericbarthelet ,

Sorry for the late reply, I see the issue has been fixed - answering just in case it's of any help:
- I use Windows 10
- I ran `sls deploy` from the project root (something like `C:\Users\cohla\dev\aws-nodejs-typescript`)
- I replaced and it works. I also tried the fix from your PR and it works as well

Thanks again for your help!
