### ISSUE TITLE
Hard to migrate to Serverless version 2.0 and remove deprecation warning

### ISSUE THREAD

**Issue by a-h** [serverless/typescript#19]
I have an existing `serverless.ts` that was created with Serverless 1.x, and it uses a file (`provider.ts`) that exports the provider to the main `serverless.ts` file. This is a large project and it helps to break up the file.

I got the deprecation notice:

```
Serverless: Deprecation warning: Starting with next major version, default value of provider.lambdaHashingVersion will be equal to "20201221"                                                                                                 
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2           
```

So I attempted to add `lambdaHashingVersion` to the file. But `lambdaHashingVersion` doesn't exist in the type definition.

```typescript
import { Provider } from 'serverless/aws'
import { getIamRoleStatements } from './iamRoleStatements'
import { getEnvironment } from './environment'

export const getProvider = (stage: string): Provider => ({
  name: 'aws',
  runtime: 'nodejs12.x',
  environment: getEnvironment(stage),
  iamRoleStatements: getIamRoleStatements(stage),
  // This doesn't exist in serverless/aws: lambdaHashingVersion: "20201221",
})
```

Hunting around in Github, I found this PR https://github.com/serverless/serverless/pull/8543/files which includes a migration. So I tried to use it.

```
import type { Provider } from '@serverless/typescript';
import { getIamRoleStatements } from './iamRoleStatements'
import { getEnvironment } from './environment'

export const getProvider = (stage: string): Provider => ({
  name: 'aws',
  runtime: 'nodejs12.x',
  environment: getEnvironment(stage),
  iamRoleStatements: getIamRoleStatements(stage),
  lambdaHashingVersion: "20201221",
})
```

Unfortunately `Provider` doesn't exist. This makes it really hard to _not_ have a single massive `serverless.ts` file, and would require quite a big refactor for me to fix up.

I think this might be related to #9 but reading through the comments I wasn't 100% sure.

**Comment by fredericbarthelet** [comment]
Hi @a-h and thanks for submitting your issue.

The issue #9 is indeed related to your problem. In the mean time, you can use `AWS['provider']` to replace the `Provider` type :

```
import { AWS } from '@serverless/typescript'
import { getIamRoleStatements } from './iamRoleStatements'
import { getEnvironment } from './environment'

export const getProvider = (stage: string): AWS['provider'] => ({
  name: 'aws',
  runtime: 'nodejs12.x',
  environment: getEnvironment(stage),
  iamRoleStatements: getIamRoleStatements(stage),
  // This doesn't exist in serverless/aws: lambdaHashingVersion: "20201221",
})
```

I'll close this as a duplicate, feel free to re-open in case the tip above does not do the trick for you.
