### ISSUE TITLE
awsProvider.d.ts file has some missing/broken property types

### ISSUE THREAD

**Issue by Namstel** [serverless/typescript#2]
### Use case description

The awsProvider.d.ts file has some missing/broken property types:
- Sns filterPolicy has a broken type
- Stream is missing optional type property
- AwsFunction layers has missing type { [key: string]: string }

### Proposed solution
I created a pull request (3 weeks ago), but no answer or action has left me wondering.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49104

Also created forum post, but no answer:
https://forum.serverless.com/t/definitelytyped-awsprovider-d-ts-pull-request-waiting/13063

I would love to hear if I have to do things differently next time.

**Comment by fredericbarthelet** [comment]
Thanks for transfering @medikoo :)

Thank you for reporting your issue @Namstel and sorry for the late reply.
I reviewed your PR over at DefinitlyType repository.

This repository aims to soon replace community maintained definition in https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/serverless with automatically generated TS definition based from serverless/serverless core JSON-schema definitions.

If you want to give it a try in beta, you can `npm i --save-dev @serverless/typescript` or `yarn add --dev @serverless/typescript` and use the following line in your `serverless.ts` to import the defintion :
```
import { AWS } from '@serverless/typescript';
```

**Comment by Namstel** [comment]
That's great news, thanks for the update @fredericbarthelet :)
