### ISSUE TITLE
Service property definition only allows object type

### ISSUE THREAD

**Issue by fredericbarthelet** [serverless/typescript#3]
#  Use case description

Typescript definition generated for `service` property as of version 2.11 of the framework states the following :

```ts
service: {
  name?: {
    [k: string]: unknown;
  };
  awsKmsKeyArn?: AwsKmsArn;
};
```

This definition has 3 errors:
- `service.name` property should be typed as `string` - current JSON definition states it should follow a string pattern - see https://github.com/serverless/serverless/blob/master/lib/configSchema.js#L112
- `service.name` property is mandatory  when using `service` object definition - see  https://github.com/serverless/serverless/blob/master/lib/classes/Service.js#L105-L109
- `service` object definition is deprecated. The new preferred definition is to directly specify service name in the `service` property - see https://github.com/serverless/serverless/issues/8465

# Proposed solution

Update `configSchema` source JSON definition with the `string` definition and `name` being mandatory.
Add `type: string` where `pattern` JSON schema property is used (see http://json-schema.org/understanding-json-schema/reference/string.html#regular-expressions)

**Comment by HarrisonJackson** [comment]
For anyone blocked on this for now:
```
import type { AWS } from '@serverless/typescript';

interface Serverless extends Omit<AWS, 'service'> {
  service: {
    name: string
  };
}
const serverlessConfiguration: Serverless = {...};
```

**Comment by fredericbarthelet** [comment]
Update has been merged on serverless/serverless side, waiting for 2.13.0 release to close this issue
