### ISSUE TITLE
No support for StringList or JSON ssm variables

### ISSUE THREAD

**Issue by joepjoosten** [serverless/typescript#30]
e.g. ssm variable with the following value: `['subnet1', 'subnet2']` can't be used in the following snippet:
```
const serverlessConfiguration: AWS = {
  ...
  provider:
    ...
    vpc:
      subnetIds: '${ssm:/varname}'
```

Because subnetIds is correctly typed as an `string[]` (or some cloudformation intrinsic function), but the way variable resolving works this will never work.
The only way to resolve this is to optionally type subnetIds as a `string`, but this is technically incorrect...

How to solve?

**Comment by mikkel-pearl** [comment]
I was just literally coming to file the exact same issue for the exact same use case...

I just am resolving it the way you have displayed (with the minor adjustment of using ~split at the end of the varname) and I adjusted my local .d.ts file to accept a single string so it would compile. It's working perfectly, except now I have to maintain a fork - so it would be very helpful if this could be resolved somehow.

**Comment by fredericbarthelet** [comment]
Hi @joepjoosten, @mikkel-pearl and thanks for submitting this issue.

I'll mark it as a duplicate from #11 where the same issue of using Serverless variable pattern arise.

There is a better specification than just adding string, which could be the use of Typescript 4.1 template literal string feature :

```ts
export type ServerlessVariableSSM<P extends string> = `\${ssm:${P}}`

// no error
const subnetIds: ServerlessVariableSSM<string> = '${ssm:/varname}'

// type error
const wrongSubnetIds: ServerlessVariableSSM<string> = '${unexistingServerlessVariable:/varname}'
const wrongSubnetIds2: ServerlessVariableSSM<string> = 'subnetId'
```

If you don't mind, let's continue this discussion on the other issue tracker :)
