### ISSUE TITLE
AWS dynamodb support

### ISSUE THREAD

**Issue by movaldivia** [serverless/typescript#35]
Would be nice to have dynamodb definition.

**Comment by fredericbarthelet** [comment]
Hi @movaldivia and thanks for reporting your issue.
This repository only holds typescript definitions for the Serverless framework.

The main [serverless repository](https://github.com/serverless/serverless) is the place for your feature request. Feel free to open a dedicated issue on this repository with your feature request. Closing this here in the meantime.

Thanks
