### ISSUE TITLE
are releases in step with serverless?

### ISSUE THREAD

**Issue by herebebogans** [serverless/typescript#51]
The README states 

"This automated pipeline is triggered every time a new release of Serverless framework is available" 

serverless is at 2.59.0 (9 days ago)  but the last release here is 2.55.0 (just over a month)

**Comment by fredericbarthelet** [comment]
Hey @herebebogans, it is still semi automated at the moment.
Types generation is, trigger isn't. I just launched the process for v2.59.0.
