### ISSUE TITLE
serverless v3 support

### ISSUE THREAD

**Issue by xr0master** [serverless/typescript#53]
Are there any plans to release types for version 3?
We are waiting for the new syntax support :)

**Comment by fredericbarthelet** [comment]
Hey @xr0master and thanks for submitting this issue.
At this moment, v3 only removes a few attributes. In any case, I just published a version to npm with tag `pre-3.0.0`. Feel free to use it :)

**Comment by xr0master** [comment]
Hi, @fredericbarthelet and thank you a lot! It was fast :)
It does not only remove a few things but also adds a new syntax and deprecates other staff. It would be nice to switch to the new syntax.
For example the `aim*` [options](https://www.serverless.com/framework/docs/guides/upgrading-v3#deprecated-features-that-will-be-kept-in-v3)

**Comment by fredericbarthelet** [comment]
Hi @xr0master , thanks for sharing an exemple. However, in particular for `provider. iamRoleStatements` being deprecated in favor of `provider.iam.role.statements`, both input were already accepted in this library for `v2.xx` (deprecations are not marked in a particular way in the Typescript definition) and remain accepted in `v3.xx` as it was too costy to actually remove them and force people tu update their package.

Do no hesitate to reply to this thread if something looks wrong in `pre-3` version of those definitions.

**Comment by xr0master** [comment]
Oh, sorry, I didn't notice that you added support for new interfaces. I got confused by the expression: "v3 only removes a few attributes" :)
It works very smoothly! Thank you.
