### ISSUE TITLE
Question: Any guidebook of how to set up serverless.ts for deployment?

### ISSUE THREAD

**Issue by SimonSongCA** [serverless/typescript#58]
I was assigned to do a deployment of my service including the Dynamodb onto AWS. I was given a sample of how the service should be deployed, but I have no idea how to systematically follow the pattern of how the serverless.ts I should leverage.

I noticed that @severless/typescript contains many variable formats, but how can these variables be configured correctly, and how can I make sure that I am not missing anything or doing anything wrong?

Any formal document or docs are greatly appreciated! This is my first time using such a framework to do the deployment, and I do hope someone could help me make my first step. 

I will certainly do the reading stuff and the hard work on my own, but it seems that I need a little guidance for the first step.

Thank you guys! Love you guys!

**Comment by fredericbarthelet** [comment]
Hey @SimonSongCA, thanks for reaching out and welcome to your serverless journey !
`serverless.yml`, `serverless.json`, `serverless.js` and `serverless.ts` are not configured differently, they are just written using different syntax. You can follow this documentation to find out more about those 4 service file formats: https://www.serverless.com/framework/docs/providers/aws/guide/intro#services

If you're looking for help starting out with everything setup correctly, use `aws-nodejs-typescript` exemple service. You can run `sls create --template aws-nodejs-typescript` or go to https://github.com/serverless/serverless/tree/master/lib/plugins/create/templates/aws-nodejs-typescript to check it out.

I'm closing this issue in the meantime as this repo only purpose is to host service file TypeScript definitions.
