### ISSUE TITLE
function destinations do not support CloudFront intrinsic functions

### ISSUE THREAD

**Issue by simonmellor** [serverless/typescript#61]
In the documentation for functions there is an example of usage for destinations where CloudFront functions are used. This is not possible to achieve using the typescript AWS interface which specifies a string for onSuccess and onFailure.

https://www.serverless.com/framework/docs/providers/aws/guide/functions#destinations

**Comment by fredericbarthelet** [comment]
Hi @simonmellor, thanks for your feedback.
The Typescript definition referring to `onSuccess` and `onFailure` property for each fonction is detailed hereafter:

https://github.com/serverless/typescript/blob/66ebd87f9516ca2116b0f3e02ae8c9007333dfbb/index.d.ts#L595-L608

This definition allows `string` as well as objects with an `arn` property refering to `AwsCfFunction`. The definition for such type is defined as

https://github.com/serverless/typescript/blob/66ebd87f9516ca2116b0f3e02ae8c9007333dfbb/index.d.ts#L10

allowing various kind of Cloudformation intrinsic functions.

Could you share a code snippet where you're facing a Typescript issue ?

**Comment by simonmellor** [comment]
Thank you @fredericbarthelet the update has resolved the issue I was facing.
