### ISSUE TITLE
Type for index.ts

### ISSUE THREAD

**Issue by redeemefy** [serverless/typescript#64]
Does the type for the `index.ts` exists? If so, can we share sample code on how to add types for the  `index.ts`?

Thanks

**Comment by mnapoli** [comment]
I don't understand your question, there are types in this file: https://github.com/serverless/typescript/blob/master/index.d.ts

**Comment by redeemefy** [comment]
In a serverless/typescript project a function has two files, `handler.ts` and `index.ts`. The handler type is coming from `aws-lambda` and one of the type could be `APIGatewayProxyHandler`. I'm wondering if the type of `function/index.ts` could come from serverless types if so, what the type would be?

**Comment by mnapoli** [comment]
I don't know the answer to that unfortunately.

Let's open discussions for questions in the GitHub discussions here: https://github.com/serverless/serverless/discussions

We'll keep this issue tracker for issues/features discussions.

**Comment by jseashell** [comment]
@redeemefy 

It's possible. Using this in production today.

```
import { AWS } from '@serverless/typescript';

type AwsFunction = AWS['functions'][0];

export default {
    handler: `${handlerPath(__dirname)}/handler.main`,
    // ...
} as AwsFunction;
```

Source: https://javascript.plainenglish.io/how-to-start-typescript-node-aws-function-with-serverlessjs-ef4b55910127

**Comment by premraval-pr** [comment]
> type AwsFunction = AWS['functions'][0];

This was an immense help. Kudos to you 🔥

SLAYYY
