### ISSUE TITLE
Support for TS 4.7?

### ISSUE THREAD

**Issue by gtamas** [serverless/typescript#66]
Serverless works with TS 4.6.x, but after upgrading to 4.7 (latest), I get this when running serverless-offline:

"Cannot load "serverless.ts": Initialization error: Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself."

I'm using Node 14.18 and these:

├── @serverless/typescript@3.19.0 
├── serverless@3.21.0 
├── serverless-offline@8.8.1 
└── typescript@4.7.4 

Is TS 4.7 not supported? If it isn't, any plans to add support?

Thx

**Comment by fredericbarthelet** [comment]
Hi @gtamas and thanks for submitting this issue.
While this is not related to this repository, I suggest you try the following :

- identify which project is not using latest version of `resolveTypeReferenceDirectives`. Try removing all plugins from your service definition file and run `sls print` or `sls package` commands.
  - If your service is working without any plugins flawlessly, try adding back plugins one by one until you hit the same issue again. You can them submit an issue within the corresponding plugin repository.
  - If your service is not working without any plugins, issue may come from https://github.com/serverless/serverless directly, and especially the `ts-node` version in use in the project. You can submit a PR in this repo to update `ts-node` version
  
I'm closing this issue in the meantime as not related to this repository.

**Comment by gtamas** [comment]
ok thx!
