### ISSUE TITLE
When does npm module get published?

### ISSUE THREAD

**Issue by herebebogans** [serverless/typescript#69]
Can see tags in the project for 3.23.0 but the latest version available on npm is 3.21.0 from 4 months ago?

**Comment by kopertop** [comment]
Nodejs18.x was introduced in Serverless Framework 3.25.0, but this module is still stuck on 3.21.0.

**Comment by AlanTaranti** [comment]
I think it's related to the broken Workflow issue https://github.com/serverless/typescript/issues/71

**Comment by fredericbarthelet** [comment]
The publishing workflow is now fixed 🎉 Version 3.25.0 of @serverless/typescript has just been released !
Thanks for your patience @AlanTaranti @kopertop @herebebogans
