### ISSUE TITLE
Broken Workflow

### ISSUE THREAD

**Issue by AlanTaranti** [serverless/typescript#71]
Since serverless 3.22 release, this project workflow is broken.

Please see: https://github.com/serverless/typescript/actions/workflows/definitionsBuilder.yml

![image](https://user-images.githubusercontent.com/9096525/203152946-dfb59d84-cd02-4a79-a091-71e20909d845.png)

**Comment by fredericbarthelet** [comment]
Indeed @AlanTaranti, thanks for pointing that out. It seems my npm token is not valid anymore. @medikoo could you update the NPM_TOKEN in this repository or send me a new one for me to update :) ?

**Comment by medikoo** [comment]
@fredericbarthelet, I think you've been accidentally removed from our npm group related to this package, sorry about that. I've resent the invite. After accepting it, I believe it should work again

**Comment by fredericbarthelet** [comment]
Thanks @medikoo. I accepted the invitation and the publishing workflow is now fixed 🎉 Version 3.25.0 of @serverless/typescript has just been released !
