### ISSUE TITLE
varying VPC settings for dev and prod environments

### ISSUE THREAD

**Issue by filenda** [serverless/typescript#76]
how to implement different vpc settings for each stage/env?

chatgpt suggested this, but it didn't work bc it needs to be strongly typed.

How would you guys work around that?

````
import type { AWS } from '@serverless/typescript';

const serverlessConfiguration: AWS = {
  service: 'my-service',
  provider: {
    name: 'aws',
    runtime: 'nodejs12.x',
    region: 'us-east-1',
    stage: '${opt:stage, "dev"}',
    vpc: '${self:custom.vpc.${self:provider.stage}, {}}', // include VPC settings only if defined
  },
  custom: {
    vpc: {
      prod: {
        securityGroupIds: ['sg-0123456789abcdef'],
        subnetIds: ['subnet-0123456789abcdef', 'subnet-0123456789abcdef'],
      },
    },
  },
  // ... rest of the serverless configuration
};

module.exports = serverlessConfiguration;
```

**Comment by fayyozbobokulov** [comment]
Her what found might be useful. Try this out. 
```
vpc: {
            subnetIds: {
                'Fn::Split': [
                    ',',
                    "${file(serverless-vpc.yml):${self:provider.stage, 'dev'}.subnetIds}",
                ],
            },
            securityGroupIds: {
                'Fn::Split': [
                    ',',
                    "${file(serverless-vpc.yml):${self:provider.stage, 'dev'}.securityGroupIds}",
                ],
            },
        },
```

**Comment by filenda** [comment]
> Her what found might be useful. Try this out.
> 
> ```
> vpc: {
>             subnetIds: {
>                 'Fn::Split': [
>                     ',',
>                     "${file(serverless-vpc.yml):${self:provider.stage, 'dev'}.subnetIds}",
>                 ],
>             },
>             securityGroupIds: {
>                 'Fn::Split': [
>                     ',',
>                     "${file(serverless-vpc.yml):${self:provider.stage, 'dev'}.securityGroupIds}",
>                 ],
>             },
>         },
> ```

hey @fayyozbobokulov tks for the interaction.

how would you write these yml files? and would these files able to be native '.ts' ones?

**Comment by fayyozbobokulov** [comment]
@filenda You can write in ts as well I think. Rather than yml. Initially, i could not make it work so I left some yml files. So, curretly I am exploring ways to use fully ts instead of yml. Mainly got from Documentation and trial and error.

**Comment by filenda** [comment]
@fayyozbobokulov your example did work. I'm figuring out now how to make it return somewhat of a "null" value whenever I wanted no vpc settings for a specific environemnt. AWS doen't accept an empty array, which is silly but they don't.
